# Generated by Django 2.2.6 on 2019-12-14 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('img', models.ImageField(upload_to='img')),
                ('desc', models.TextField()),
                ('price', models.FloatField()),
                ('offer', models.BooleanField(default=False)),
            ],
        ),
    ]
