# Generated by Django 2.2.6 on 2019-12-31 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finitfarm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Frozen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('des', models.TextField()),
                ('img', models.ImageField(upload_to='img')),
            ],
        ),
    ]
