# Generated by Django 2.2.6 on 2019-12-31 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BreedProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('img', models.ImageField(upload_to='img')),
                ('offer', models.BooleanField(default=False)),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='FrozonProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('img', models.ImageField(upload_to='img')),
                ('offer', models.BooleanField(default=False)),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='LiveProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('img', models.ImageField(upload_to='img')),
                ('offer', models.BooleanField(default=False)),
                ('price', models.FloatField()),
            ],
        ),
    ]
